import React, { useState, useEffect } from 'react';
import {
  DollarSign, Plus, Search, Filter, Edit, Trash2, Eye, Download, FileText,
  Calculator, CheckCircle, X, Calendar, User, Building2, Clock, AlertCircle,
  TrendingUp, Minus, Save, RefreshCw, FileSpreadsheet, Zap, Users, BarChart3
} from 'lucide-react';
import { supabase } from '../../lib/supabase';
import {
  PayrollSettlement,
  SettlementWithDetails,
  SettlementFormData,
  SettlementSummary,
  HourType,
  IncidentType,
  DeductionType,
  IncomeType
} from '../../types/settlements';
import { Worker } from '../../types/construction';
import { exportToPDF, exportToExcel } from '../../utils/exportUtils';
import { formatCurrency, formatNumber } from '../../utils/formatUtils';

const SettlementsModuleEnhanced: React.FC = () => {
  const [activeView, setActiveView] = useState<'list' | 'form' | 'detail' | 'auto-generate' | 'reports'>('list');
  const [settlements, setSettlements] = useState<SettlementWithDetails[]>([]);
  const [workers, setWorkers] = useState<Worker[]>([]);
  const [projects, setProjects] = useState<any[]>([]);
  const [workReports, setWorkReports] = useState<any[]>([]);
  const [selectedSettlement, setSelectedSettlement] = useState<SettlementWithDetails | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [filterMonth, setFilterMonth] = useState<number>(new Date().getMonth() + 1);
  const [filterYear, setFilterYear] = useState<number>(new Date().getFullYear());
  const [filterProject, setFilterProject] = useState<string>('all');
  const [notification, setNotification] = useState({ show: false, message: '', type: '' });
  const [summary, setSummary] = useState<SettlementSummary>({
    total_settlements: 0,
    total_gross_amount: 0,
    total_deductions: 0,
    total_net_amount: 0,
    settlements_by_status: { draft: 0, calculated: 0, approved: 0, paid: 0 }
  });

  const [autoGenerateData, setAutoGenerateData] = useState({
    period_month: new Date().getMonth() + 1,
    period_year: new Date().getFullYear(),
    project_id: '',
    selected_workers: [] as string[],
    period_start: '',
    period_end: ''
  });

  const [formData, setFormData] = useState<SettlementFormData>({
    settlement_code: '',
    worker_id: '',
    project_id: '',
    period_month: new Date().getMonth() + 1,
    period_year: new Date().getFullYear(),
    base_salary: 0,
    notes: '',
    hours: [],
    incidents: [],
    deductions: [],
    additional_income: []
  });

  useEffect(() => {
    loadData();
  }, [filterMonth, filterYear, filterStatus, filterProject]);

  const loadData = async () => {
    setIsLoading(true);
    try {
      await Promise.all([
        loadSettlements(),
        loadWorkers(),
        loadProjects(),
        loadWorkReports()
      ]);
    } catch (error: any) {
      showNotification('Error al cargar datos: ' + error.message, 'error');
    } finally {
      setIsLoading(false);
    }
  };

  const loadSettlements = async () => {
    let query = supabase
      .from('payroll_settlements')
      .select('*')
      .eq('period_month', filterMonth)
      .eq('period_year', filterYear);

    if (filterStatus !== 'all') {
      query = query.eq('status', filterStatus);
    }

    if (filterProject !== 'all') {
      query = query.eq('project_id', filterProject);
    }

    const { data, error } = await query.order('created_at', { ascending: false });

    if (error) throw error;

    const settlementsWithDetails: SettlementWithDetails[] = await Promise.all(
      (data || []).map(async (settlement) => {
        const [hoursRes, incidentsRes, deductionsRes, incomeRes, workerRes, projectRes] = await Promise.all([
          supabase.from('settlement_hours').select('*').eq('settlement_id', settlement.id),
          supabase.from('settlement_incidents').select('*').eq('settlement_id', settlement.id),
          supabase.from('settlement_deductions').select('*').eq('settlement_id', settlement.id),
          supabase.from('settlement_additional_income').select('*').eq('settlement_id', settlement.id),
          supabase.from('workers').select('first_name, last_name').eq('id', settlement.worker_id).maybeSingle(),
          settlement.project_id ? supabase.from('projects').select('name').eq('id', settlement.project_id).maybeSingle() : Promise.resolve({ data: null })
        ]);

        return {
          ...settlement,
          worker_name: workerRes.data ? `${workerRes.data.first_name} ${workerRes.data.last_name}` : 'N/A',
          project_name: projectRes.data?.name || 'General',
          hours: hoursRes.data || [],
          incidents: incidentsRes.data || [],
          deductions: deductionsRes.data || [],
          additional_income: incomeRes.data || []
        };
      })
    );

    setSettlements(settlementsWithDetails);
    calculateSummary(settlementsWithDetails);
  };

  const loadWorkers = async () => {
    const { data, error } = await supabase
      .from('workers')
      .select('*')
      .eq('status', 'active')
      .order('first_name');

    if (error) throw error;

    const transformedWorkers: Worker[] = (data || []).map((w: any) => ({
      id: w.id,
      workerCode: w.worker_code,
      name: `${w.first_name} ${w.last_name}`,
      personalData: {
        firstName: w.first_name,
        lastName: w.last_name,
        dni: w.dni,
        dniExpiryDate: w.dni_expiry_date,
        address: w.address || '',
        city: w.city || '',
        postalCode: w.postal_code || '',
        phone: w.phone || '',
        email: w.email || '',
        emergencyContact: w.emergency_contact || '',
        emergencyPhone: w.emergency_phone || '',
        hasDriverLicense: w.has_driver_license,
        hasOwnVehicle: w.has_own_vehicle
      },
      professionalData: {
        category: w.category,
        prlType: w.prl_type || '',
        prlTraining: [],
        prlExpiryDate: w.prl_expiry_date || '',
        medicalCheckDate: w.medical_check_date || '',
        medicalCheckExpiry: w.medical_check_expiry || '',
        epiDeliveryDate: w.epi_delivery_date || ''
      },
      contractData: {
        contractType: w.contract_type,
        hourlyRate: w.hourly_rate || 0,
        overtimeRate: w.overtime_rate || 0,
        hireDate: w.hire_date || '',
        vacationTotalDays: w.vacation_total_days || 30,
        vacationUsedDays: w.vacation_used_days || 0,
        vacationPendingDays: w.vacation_pending_days || 0,
        contractSigned: w.contract_signed || false,
        bankAccount: w.bank_account || '',
        digitalAccessUsername: w.digital_access_username || '',
        digitalAccessPassword: w.digital_access_password || ''
      },
      status: w.status,
      category: w.category
    }));

    setWorkers(transformedWorkers);
  };

  const loadProjects = async () => {
    const { data, error } = await supabase
      .from('projects')
      .select('id, name, code')
      .eq('status', 'active')
      .order('name');

    if (error) throw error;
    setProjects(data || []);
  };

  const loadWorkReports = async () => {
    const { data, error } = await supabase
      .from('work_reports')
      .select('*')
      .eq('status', 'closed')
      .order('report_date', { ascending: false });

    if (error) throw error;
    setWorkReports(data || []);
  };

  const calculateSummary = (settlementsData: SettlementWithDetails[]) => {
    const summaryData: SettlementSummary = {
      total_settlements: settlementsData.length,
      total_gross_amount: settlementsData.reduce((sum, s) => sum + Number(s.gross_amount), 0),
      total_deductions: settlementsData.reduce((sum, s) => sum + Number(s.total_deductions), 0),
      total_net_amount: settlementsData.reduce((sum, s) => sum + Number(s.net_amount), 0),
      settlements_by_status: {
        draft: settlementsData.filter(s => s.status === 'draft').length,
        calculated: settlementsData.filter(s => s.status === 'calculated').length,
        approved: settlementsData.filter(s => s.status === 'approved').length,
        paid: settlementsData.filter(s => s.status === 'paid').length
      }
    };
    setSummary(summaryData);
  };

  const handleAutoGenerate = async () => {
    if (autoGenerateData.selected_workers.length === 0) {
      showNotification('Seleccione al menos un operario', 'error');
      return;
    }

    if (!autoGenerateData.period_start || !autoGenerateData.period_end) {
      showNotification('Seleccione el rango de fechas', 'error');
      return;
    }

    setIsLoading(true);

    try {
      for (const workerId of autoGenerateData.selected_workers) {
        const worker = workers.find(w => w.id === workerId);
        if (!worker) continue;

        let reportsQuery = supabase
          .from('work_reports')
          .select('*')
          .eq('status', 'closed')
          .gte('report_date', autoGenerateData.period_start)
          .lte('report_date', autoGenerateData.period_end);

        if (autoGenerateData.project_id) {
          reportsQuery = reportsQuery.eq('project_id', autoGenerateData.project_id);
        }

        const { data: workerReports } = await reportsQuery;

        const hoursData: any[] = [];
        let totalHours = 0;

        if (workerReports && workerReports.length > 0) {
          const normalHours = workerReports.reduce((sum, r) => sum + (r.hours_worked || 0), 0);
          const overtimeHours = workerReports.reduce((sum, r) => sum + (r.overtime_hours || 0), 0);

          if (normalHours > 0) {
            hoursData.push({
              hour_type: 'normal',
              hours: normalHours,
              rate: worker.contractData.hourlyRate,
              description: 'Horas regulares desde partes de trabajo'
            });
            totalHours += normalHours;
          }

          if (overtimeHours > 0) {
            hoursData.push({
              hour_type: 'overtime',
              hours: overtimeHours,
              rate: worker.contractData.overtimeRate || worker.contractData.hourlyRate * 1.5,
              description: 'Horas extra desde partes de trabajo'
            });
            totalHours += overtimeHours;
          }
        }

        const hoursTotal = hoursData.reduce((sum, h) => sum + (h.hours * h.rate), 0);
        const baseSalary = worker.contractData.hourlyRate * 160;
        const grossAmount = baseSalary + hoursTotal;

        const irpfRate = 0.15;
        const irpfAmount = grossAmount * irpfRate;
        const ssRate = 0.047;
        const ssAmount = grossAmount * ssRate;
        const totalDeductions = irpfAmount + ssAmount;
        const netAmount = grossAmount - totalDeductions;

        const nextCode = `LIQ-${autoGenerateData.period_year}-${String(autoGenerateData.period_month).padStart(2, '0')}-${String(Math.random()).substring(2, 6)}`;

        const { data: newSettlement, error: insertError } = await supabase
          .from('payroll_settlements')
          .insert({
            settlement_code: nextCode,
            worker_id: workerId,
            project_id: autoGenerateData.project_id || null,
            period_month: autoGenerateData.period_month,
            period_year: autoGenerateData.period_year,
            base_salary: baseSalary,
            total_hours_worked: totalHours,
            gross_amount: grossAmount,
            total_deductions: totalDeductions,
            total_additional_income: 0,
            net_amount: netAmount,
            status: 'calculated',
            auto_calculated: true,
            work_reports_period_start: autoGenerateData.period_start,
            work_reports_period_end: autoGenerateData.period_end,
            created_by: 'Admin'
          })
          .select()
          .single();

        if (insertError) throw insertError;

        if (hoursData.length > 0) {
          const hoursToInsert = hoursData.map(h => ({
            settlement_id: newSettlement.id,
            hour_type: h.hour_type,
            hours: h.hours,
            rate: h.rate,
            description: h.description
          }));
          await supabase.from('settlement_hours').insert(hoursToInsert);
        }

        await supabase.from('settlement_deductions').insert([
          {
            settlement_id: newSettlement.id,
            deduction_type: 'irpf',
            amount: irpfAmount,
            percentage: irpfRate * 100,
            description: 'Retención IRPF automática'
          },
          {
            settlement_id: newSettlement.id,
            deduction_type: 'social_security',
            amount: ssAmount,
            percentage: ssRate * 100,
            description: 'Seguridad Social'
          }
        ]);

        if (workerReports && workerReports.length > 0) {
          const links = workerReports.map(wr => ({
            settlement_id: newSettlement.id,
            work_report_id: wr.id,
            hours_counted: (wr.hours_worked || 0) + (wr.overtime_hours || 0)
          }));
          await supabase.from('settlement_work_report_links').insert(links);
        }
      }

      showNotification(`${autoGenerateData.selected_workers.length} liquidaciones generadas correctamente`, 'success');
      setActiveView('list');
      loadSettlements();
    } catch (error: any) {
      showNotification('Error al generar liquidaciones: ' + error.message, 'error');
    } finally {
      setIsLoading(false);
    }
  };

  const handleExportDetailedReport = async () => {
    const { data, error } = await supabase
      .from('settlement_detailed_report')
      .select('*')
      .eq('period_month', filterMonth)
      .eq('period_year', filterYear);

    if (error) {
      showNotification('Error al generar reporte: ' + error.message, 'error');
      return;
    }

    const exportData = (data || []).map((s: any) => ({
      'Código Liquidación': s.settlement_code,
      'Código Operario': s.worker_code,
      'Operario': s.worker_name,
      'Código Obra': s.project_code || 'N/A',
      'Obra': s.project_name || 'General',
      'Período': `${s.period_month}/${s.period_year}`,
      'Salario Base': s.base_salary,
      'Horas Trabajadas': s.total_hours_worked,
      'Bruto': s.gross_amount,
      'Deducciones': s.total_deductions,
      'Ingresos Adicionales': s.total_additional_income,
      'Neto': s.net_amount,
      'Estado': s.status,
      'Auto-calculado': s.auto_calculated ? 'Sí' : 'No',
      'Entradas Horas': s.hours_entries,
      'Incidencias': s.incidents_count,
      'Descuentos': s.deductions_count,
      'Ingresos': s.income_entries
    }));

    const excelData = {
      title: `Reporte Detallado Liquidaciones ${filterMonth}/${filterYear}`,
      headers: Object.keys(exportData[0] || {}),
      data: exportData,
      filename: `reporte_detallado_liquidaciones_${filterYear}_${filterMonth}`
    };

    exportToExcel(excelData);
  };

  const handleExportByProject = async () => {
    const { data, error } = await supabase
      .from('settlement_summary_by_project')
      .select('*')
      .eq('period_month', filterMonth)
      .eq('period_year', filterYear);

    if (error) {
      showNotification('Error al generar reporte: ' + error.message, 'error');
      return;
    }

    const exportData = (data || []).map((s: any) => ({
      'Obra': s.project_name || 'General',
      'Período': `${s.period_month}/${s.period_year}`,
      'Total Liquidaciones': s.total_settlements,
      'Total Horas': s.total_hours,
      'Total Bruto': s.total_gross,
      'Total Deducciones': s.total_deductions,
      'Total Neto': s.total_net
    }));

    const excelData = {
      title: `Resumen por Obra ${filterMonth}/${filterYear}`,
      headers: Object.keys(exportData[0] || {}),
      data: exportData,
      filename: `resumen_por_obra_${filterYear}_${filterMonth}`
    };

    exportToExcel(excelData);
  };

  const handleViewDetail = async (settlementId: string) => {
    console.log('🔍 Cargando detalle de liquidación:', settlementId);
    const settlement = settlements.find(s => s.id === settlementId);
    if (!settlement) {
      showNotification('Liquidación no encontrada', 'error');
      return;
    }

    setSelectedSettlement(settlement);
    setActiveView('detail');
    console.log('✅ Vista de detalle cargada:', settlement);
  };

  const handleEdit = (settlementId: string) => {
    console.log('✏️ Editando liquidación:', settlementId);
    const settlement = settlements.find(s => s.id === settlementId);
    if (!settlement) {
      showNotification('Liquidación no encontrada', 'error');
      return;
    }

    if (settlement.status === 'paid') {
      showNotification('No se puede editar una liquidación pagada', 'error');
      return;
    }

    setFormData({
      settlement_code: settlement.settlement_code,
      worker_id: settlement.worker_id,
      project_id: settlement.project_id,
      period_month: settlement.period_month,
      period_year: settlement.period_year,
      base_salary: settlement.base_salary,
      notes: settlement.notes || '',
      hours: settlement.hours || [],
      incidents: settlement.incidents || [],
      deductions: settlement.deductions || [],
      additional_income: settlement.additional_income || []
    });

    setSelectedSettlement(settlement);
    setActiveView('form');
    console.log('✅ Modo edición activado');
  };

  const handleDelete = async (settlementId: string) => {
    const settlement = settlements.find(s => s.id === settlementId);
    if (!settlement) {
      showNotification('Liquidación no encontrada', 'error');
      return;
    }

    if (settlement.status === 'paid') {
      showNotification('No se puede eliminar una liquidación pagada', 'error');
      return;
    }

    if (!confirm(`¿Eliminar la liquidación ${settlement.settlement_code}?\n\nOperario: ${settlement.worker_name}\nPeríodo: ${settlement.period_month}/${settlement.period_year}\n\nEsta acción no se puede deshacer.`)) {
      return;
    }

    console.log('🗑️ Eliminando liquidación:', settlementId);
    setIsLoading(true);

    try {
      const { error } = await supabase
        .from('payroll_settlements')
        .delete()
        .eq('id', settlementId);

      if (error) throw error;

      showNotification('✅ Liquidación eliminada correctamente', 'success');
      console.log('✅ Liquidación eliminada exitosamente');
      loadData();
    } catch (error: any) {
      console.error('❌ Error al eliminar liquidación:', error);
      showNotification('Error al eliminar: ' + error.message, 'error');
    } finally {
      setIsLoading(false);
    }
  };

  const handleExportIndividualReport = async (settlementId: string) => {
    const settlement = settlements.find(s => s.id === settlementId);
    if (!settlement) return;

    const exportData = [
      { Concepto: 'INFORMACIÓN GENERAL', Detalle: '', Importe: '' },
      { Concepto: 'Código Liquidación', Detalle: settlement.settlement_code, Importe: '' },
      { Concepto: 'Operario', Detalle: settlement.worker_name, Importe: '' },
      { Concepto: 'Obra', Detalle: settlement.project_name, Importe: '' },
      { Concepto: 'Período', Detalle: `${settlement.period_month}/${settlement.period_year}`, Importe: '' },
      { Concepto: '', Detalle: '', Importe: '' },
      { Concepto: 'SALARIO BASE', Detalle: '', Importe: `€${settlement.base_salary.toFixed(2)}` },
      { Concepto: '', Detalle: '', Importe: '' },
      { Concepto: 'HORAS TRABAJADAS', Detalle: '', Importe: '' },
      ...settlement.hours.map(h => ({
        Concepto: h.hour_type,
        Detalle: `${h.hours}h x €${h.rate.toFixed(2)}`,
        Importe: `€${h.amount.toFixed(2)}`
      })),
      { Concepto: '', Detalle: '', Importe: '' },
      { Concepto: 'INGRESOS ADICIONALES', Detalle: '', Importe: '' },
      ...settlement.additional_income.map(ai => ({
        Concepto: ai.income_type,
        Detalle: ai.description || '',
        Importe: `€${ai.amount.toFixed(2)}`
      })),
      { Concepto: '', Detalle: '', Importe: '' },
      { Concepto: 'TOTAL BRUTO', Detalle: '', Importe: `€${settlement.gross_amount.toFixed(2)}` },
      { Concepto: '', Detalle: '', Importe: '' },
      { Concepto: 'DESCUENTOS', Detalle: '', Importe: '' },
      ...settlement.deductions.map(d => ({
        Concepto: d.deduction_type,
        Detalle: d.description || '',
        Importe: `-€${d.amount.toFixed(2)}`
      })),
      ...settlement.incidents.filter(i => i.affects_payment).map(i => ({
        Concepto: `Incidencia: ${i.incident_type}`,
        Detalle: i.description || '',
        Importe: `-€${i.discount_amount.toFixed(2)}`
      })),
      { Concepto: '', Detalle: '', Importe: '' },
      { Concepto: 'TOTAL NETO A PAGAR', Detalle: '', Importe: `€${settlement.net_amount.toFixed(2)}` }
    ];

    const excelData = {
      title: `Liquidación Individual - ${settlement.worker_name}`,
      headers: ['Concepto', 'Detalle', 'Importe'],
      data: exportData,
      filename: `liquidacion_${settlement.settlement_code}`
    };

    exportToExcel(excelData);
  };

  const showNotification = (message: string, type: string) => {
    setNotification({ show: true, message, type });
    setTimeout(() => setNotification({ show: false, message: '', type: '' }), 3000);
  };

  const getStatusBadge = (status: string) => {
    const badges = {
      draft: 'bg-gray-100 text-gray-800',
      calculated: 'bg-blue-100 text-blue-800',
      approved: 'bg-green-100 text-green-800',
      paid: 'bg-purple-100 text-purple-800'
    };
    const labels = {
      draft: 'Borrador',
      calculated: 'Calculado',
      approved: 'Aprobado',
      paid: 'Pagado'
    };
    return (
      <span className={`px-2 py-1 text-xs font-semibold rounded-full ${badges[status as keyof typeof badges]}`}>
        {labels[status as keyof typeof labels]}
      </span>
    );
  };

  const filteredSettlements = settlements.filter(s =>
    s.worker_name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    s.settlement_code.toLowerCase().includes(searchTerm.toLowerCase())
  );

  if (activeView === 'auto-generate') {
    return (
      <div className="space-y-6">
        {notification.show && (
          <div className={`fixed top-4 right-4 px-6 py-3 rounded-lg shadow-lg z-50 ${
            notification.type === 'success' ? 'bg-green-500' : 'bg-red-500'
          } text-white`}>
            {notification.message}
          </div>
        )}

        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-2xl font-bold text-gray-900">Generación Automática de Liquidaciones</h3>
            <p className="text-gray-600">Desde partes de trabajo cerrados</p>
          </div>
          <button
            onClick={() => setActiveView('list')}
            className="text-gray-500 hover:text-gray-700"
          >
            <X className="w-6 h-6" />
          </button>
        </div>

        <div className="bg-white rounded-lg shadow-md p-6 space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Mes</label>
              <select
                value={autoGenerateData.period_month}
                onChange={(e) => setAutoGenerateData({ ...autoGenerateData, period_month: parseInt(e.target.value) })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg"
              >
                {Array.from({ length: 12 }, (_, i) => i + 1).map(month => (
                  <option key={month} value={month}>
                    {new Date(2024, month - 1).toLocaleString('es', { month: 'long' })}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Año</label>
              <input
                type="number"
                min="2020"
                value={autoGenerateData.period_year}
                onChange={(e) => setAutoGenerateData({ ...autoGenerateData, period_year: parseInt(e.target.value) })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Fecha Inicio Período</label>
              <input
                type="date"
                value={autoGenerateData.period_start}
                onChange={(e) => setAutoGenerateData({ ...autoGenerateData, period_start: e.target.value })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg"
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">Fecha Fin Período</label>
              <input
                type="date"
                value={autoGenerateData.period_end}
                onChange={(e) => setAutoGenerateData({ ...autoGenerateData, period_end: e.target.value })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg"
              />
            </div>

            <div className="md:col-span-2">
              <label className="block text-sm font-medium text-gray-700 mb-2">Obra (Opcional)</label>
              <select
                value={autoGenerateData.project_id}
                onChange={(e) => setAutoGenerateData({ ...autoGenerateData, project_id: e.target.value })}
                className="w-full px-4 py-2 border border-gray-300 rounded-lg"
              >
                <option value="">Todas las obras</option>
                {projects.map(project => (
                  <option key={project.id} value={project.id}>{project.name}</option>
                ))}
              </select>
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">Seleccionar Operarios</label>
            <div className="border border-gray-300 rounded-lg p-4 max-h-96 overflow-y-auto space-y-2">
              {workers.map(worker => (
                <label key={worker.id} className="flex items-center gap-3 p-2 hover:bg-gray-50 rounded">
                  <input
                    type="checkbox"
                    checked={autoGenerateData.selected_workers.includes(worker.id)}
                    onChange={(e) => {
                      if (e.target.checked) {
                        setAutoGenerateData({
                          ...autoGenerateData,
                          selected_workers: [...autoGenerateData.selected_workers, worker.id]
                        });
                      } else {
                        setAutoGenerateData({
                          ...autoGenerateData,
                          selected_workers: autoGenerateData.selected_workers.filter(id => id !== worker.id)
                        });
                      }
                    }}
                    className="w-4 h-4"
                  />
                  <span className="font-medium">{worker.name}</span>
                  <span className="text-sm text-gray-500">({worker.category})</span>
                </label>
              ))}
            </div>
          </div>

          <div className="flex gap-3 pt-6 border-t">
            <button
              onClick={() => setActiveView('list')}
              className="px-6 py-3 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
            >
              Cancelar
            </button>
            <button
              onClick={handleAutoGenerate}
              disabled={isLoading}
              className="flex items-center gap-2 px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:opacity-50"
            >
              <Zap className="w-5 h-5" />
              {isLoading ? 'Generando...' : 'Generar Liquidaciones'}
            </button>
          </div>
        </div>
      </div>
    );
  }

  if (activeView === 'detail' && selectedSettlement) {
    return (
      <div className="space-y-6">
        {notification.show && (
          <div className={`fixed top-4 right-4 px-6 py-3 rounded-lg shadow-lg z-50 ${
            notification.type === 'success' ? 'bg-green-500' : 'bg-red-500'
          } text-white`}>
            {notification.message}
          </div>
        )}

        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-2xl font-bold text-gray-900">Detalle de Liquidación</h3>
            <p className="text-gray-600">{selectedSettlement.settlement_code}</p>
          </div>
          <button
            onClick={() => {
              setSelectedSettlement(null);
              setActiveView('list');
            }}
            className="flex items-center gap-2 px-4 py-2 text-gray-700 hover:text-gray-900"
          >
            <X className="w-5 h-5" />
            Cerrar
          </button>
        </div>

        <div className="bg-white rounded-lg shadow-md">
          <div className="p-6 border-b border-gray-200">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Operario</label>
                <p className="text-lg font-semibold text-gray-900">{selectedSettlement.worker_name}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Obra</label>
                <p className="text-lg font-semibold text-gray-900">{selectedSettlement.project_name}</p>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Período</label>
                <p className="text-lg font-semibold text-gray-900">
                  {selectedSettlement.period_month}/{selectedSettlement.period_year}
                </p>
              </div>
            </div>
            <div className="mt-4">
              {getStatusBadge(selectedSettlement.status)}
            </div>
          </div>

          <div className="p-6 space-y-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div className="bg-blue-50 p-4 rounded-lg">
                <p className="text-sm text-blue-600 mb-1">Salario Base</p>
                <p className="text-2xl font-bold text-blue-900">€{selectedSettlement.base_salary.toFixed(2)}</p>
              </div>
              <div className="bg-green-50 p-4 rounded-lg">
                <p className="text-sm text-green-600 mb-1">Total Bruto</p>
                <p className="text-2xl font-bold text-green-900">€{selectedSettlement.gross_amount.toFixed(2)}</p>
              </div>
              <div className="bg-purple-50 p-4 rounded-lg">
                <p className="text-sm text-purple-600 mb-1">Total Neto</p>
                <p className="text-2xl font-bold text-purple-900">€{selectedSettlement.net_amount.toFixed(2)}</p>
              </div>
            </div>

            {selectedSettlement.hours && selectedSettlement.hours.length > 0 && (
              <div>
                <h4 className="text-lg font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <Clock className="w-5 h-5" />
                  Horas Trabajadas
                </h4>
                <div className="bg-gray-50 rounded-lg overflow-hidden">
                  <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-100">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Tipo</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Horas</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Tarifa</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Total</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {selectedSettlement.hours.map((hour, idx) => (
                        <tr key={idx}>
                          <td className="px-4 py-3 text-sm text-gray-900">{hour.hour_type}</td>
                          <td className="px-4 py-3 text-sm text-gray-900">{hour.hours}h</td>
                          <td className="px-4 py-3 text-sm text-gray-900">€{hour.rate.toFixed(2)}/h</td>
                          <td className="px-4 py-3 text-sm font-semibold text-gray-900">€{hour.amount.toFixed(2)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {selectedSettlement.additional_income && selectedSettlement.additional_income.length > 0 && (
              <div>
                <h4 className="text-lg font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <TrendingUp className="w-5 h-5" />
                  Ingresos Adicionales
                </h4>
                <div className="bg-gray-50 rounded-lg overflow-hidden">
                  <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-100">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Tipo</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Descripción</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Importe</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {selectedSettlement.additional_income.map((income, idx) => (
                        <tr key={idx}>
                          <td className="px-4 py-3 text-sm text-gray-900">{income.income_type}</td>
                          <td className="px-4 py-3 text-sm text-gray-900">{income.description || '-'}</td>
                          <td className="px-4 py-3 text-sm font-semibold text-green-600">€{income.amount.toFixed(2)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {selectedSettlement.deductions && selectedSettlement.deductions.length > 0 && (
              <div>
                <h4 className="text-lg font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <Minus className="w-5 h-5" />
                  Descuentos
                </h4>
                <div className="bg-gray-50 rounded-lg overflow-hidden">
                  <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-100">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Tipo</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Descripción</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Importe</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {selectedSettlement.deductions.map((deduction, idx) => (
                        <tr key={idx}>
                          <td className="px-4 py-3 text-sm text-gray-900">{deduction.deduction_type}</td>
                          <td className="px-4 py-3 text-sm text-gray-900">{deduction.description || '-'}</td>
                          <td className="px-4 py-3 text-sm font-semibold text-red-600">-€{deduction.amount.toFixed(2)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {selectedSettlement.incidents && selectedSettlement.incidents.length > 0 && (
              <div>
                <h4 className="text-lg font-semibold text-gray-900 mb-3 flex items-center gap-2">
                  <AlertCircle className="w-5 h-5" />
                  Incidencias
                </h4>
                <div className="bg-gray-50 rounded-lg overflow-hidden">
                  <table className="min-w-full divide-y divide-gray-200">
                    <thead className="bg-gray-100">
                      <tr>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Tipo</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Fecha</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Descripción</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Afecta Pago</th>
                        <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase">Descuento</th>
                      </tr>
                    </thead>
                    <tbody className="bg-white divide-y divide-gray-200">
                      {selectedSettlement.incidents.map((incident, idx) => (
                        <tr key={idx}>
                          <td className="px-4 py-3 text-sm text-gray-900">{incident.incident_type}</td>
                          <td className="px-4 py-3 text-sm text-gray-900">{incident.incident_date}</td>
                          <td className="px-4 py-3 text-sm text-gray-900">{incident.description || '-'}</td>
                          <td className="px-4 py-3 text-sm">
                            {incident.affects_payment ? (
                              <CheckCircle className="w-5 h-5 text-red-600" />
                            ) : (
                              <X className="w-5 h-5 text-gray-400" />
                            )}
                          </td>
                          <td className="px-4 py-3 text-sm font-semibold text-red-600">
                            {incident.affects_payment ? `-${formatCurrency(incident.discount_amount)}` : '-'}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            )}

            {selectedSettlement.notes && (
              <div>
                <h4 className="text-lg font-semibold text-gray-900 mb-2">Notas</h4>
                <p className="text-sm text-gray-700 bg-gray-50 p-4 rounded-lg">{selectedSettlement.notes}</p>
              </div>
            )}
          </div>

          <div className="px-6 py-4 bg-gray-50 border-t border-gray-200 flex justify-between items-center">
            <div className="flex gap-3">
              <button
                onClick={() => handleExportIndividualReport(selectedSettlement.id)}
                className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
              >
                <Download className="w-4 h-4" />
                Exportar Excel
              </button>
              {selectedSettlement.status !== 'paid' && (
                <button
                  onClick={() => handleEdit(selectedSettlement.id)}
                  className="flex items-center gap-2 px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700"
                >
                  <Edit className="w-4 h-4" />
                  Editar
                </button>
              )}
            </div>
            <button
              onClick={() => {
                setSelectedSettlement(null);
                setActiveView('list');
              }}
              className="px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
            >
              Volver al Listado
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {notification.show && (
        <div className={`fixed top-4 right-4 px-6 py-3 rounded-lg shadow-lg z-50 ${
          notification.type === 'success' ? 'bg-green-500' : 'bg-red-500'
        } text-white`}>
          {notification.message}
        </div>
      )}

      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-gray-900">Liquidaciones</h2>
          <p className="text-gray-600">Gestión de nóminas y liquidaciones mensuales</p>
        </div>
        <div className="flex gap-3">
          <button
            onClick={handleExportDetailedReport}
            className="flex items-center gap-2 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
          >
            <BarChart3 className="w-5 h-5" />
            Reporte Detallado
          </button>
          <button
            onClick={handleExportByProject}
            className="flex items-center gap-2 px-4 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50"
          >
            <Building2 className="w-5 h-5" />
            Por Obra
          </button>
          <button
            onClick={() => setActiveView('auto-generate')}
            className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700"
          >
            <Zap className="w-5 h-5" />
            Auto-Generar
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Total Liquidaciones</p>
              <p className="text-2xl font-bold text-gray-900">{summary.total_settlements}</p>
            </div>
            <Calculator className="w-12 h-12 text-blue-600 opacity-20" />
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Bruto Total</p>
              <p className="text-2xl font-bold text-gray-900">€{summary.total_gross_amount.toFixed(2)}</p>
            </div>
            <TrendingUp className="w-12 h-12 text-green-600 opacity-20" />
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Total Descuentos</p>
              <p className="text-2xl font-bold text-red-600">€{summary.total_deductions.toFixed(2)}</p>
            </div>
            <Minus className="w-12 h-12 text-red-600 opacity-20" />
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-md p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-600">Neto Total</p>
              <p className="text-2xl font-bold text-green-600">€{summary.total_net_amount.toFixed(2)}</p>
            </div>
            <DollarSign className="w-12 h-12 text-green-600 opacity-20" />
          </div>
        </div>
      </div>

      <div className="bg-white rounded-lg shadow-md p-6 space-y-4">
        <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
            <input
              type="text"
              placeholder="Buscar..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg"
            />
          </div>

          <select
            value={filterMonth}
            onChange={(e) => setFilterMonth(parseInt(e.target.value))}
            className="px-4 py-2 border border-gray-300 rounded-lg"
          >
            {Array.from({ length: 12 }, (_, i) => i + 1).map(month => (
              <option key={month} value={month}>
                {new Date(2024, month - 1).toLocaleString('es', { month: 'long' })}
              </option>
            ))}
          </select>

          <select
            value={filterYear}
            onChange={(e) => setFilterYear(parseInt(e.target.value))}
            className="px-4 py-2 border border-gray-300 rounded-lg"
          >
            {Array.from({ length: 5 }, (_, i) => new Date().getFullYear() - i).map(year => (
              <option key={year} value={year}>{year}</option>
            ))}
          </select>

          <select
            value={filterProject}
            onChange={(e) => setFilterProject(e.target.value)}
            className="px-4 py-2 border border-gray-300 rounded-lg"
          >
            <option value="all">Todas las obras</option>
            {projects.map(project => (
              <option key={project.id} value={project.id}>{project.name}</option>
            ))}
          </select>

          <select
            value={filterStatus}
            onChange={(e) => setFilterStatus(e.target.value)}
            className="px-4 py-2 border border-gray-300 rounded-lg"
          >
            <option value="all">Todos los estados</option>
            <option value="draft">Borrador</option>
            <option value="calculated">Calculado</option>
            <option value="approved">Aprobado</option>
            <option value="paid">Pagado</option>
          </select>
        </div>
      </div>

      {isLoading ? (
        <div className="text-center py-12">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Cargando liquidaciones...</p>
        </div>
      ) : (
        <div className="bg-white rounded-lg shadow-md overflow-hidden">
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Código</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Operario</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Obra</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Período</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Bruto</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Neto</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Estado</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Acciones</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {filteredSettlements.map(settlement => (
                  <tr key={settlement.id} className="hover:bg-gray-50">
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                      {settlement.settlement_code}
                      {settlement.auto_calculated && (
                        <span className="ml-2 text-xs text-blue-600" title="Auto-calculado desde partes">⚡</span>
                      )}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{settlement.worker_name}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{settlement.project_name}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                      {settlement.period_month}/{settlement.period_year}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-semibold text-gray-900">
                      €{settlement.gross_amount.toFixed(2)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-bold text-green-600">
                      €{settlement.net_amount.toFixed(2)}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">{getStatusBadge(settlement.status)}</td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm">
                      <div className="flex gap-2">
                        <button
                          onClick={() => handleViewDetail(settlement.id)}
                          className="text-blue-600 hover:text-blue-800"
                          title="Ver detalle"
                        >
                          <Eye className="w-5 h-5" />
                        </button>
                        {settlement.status !== 'paid' && (
                          <button
                            onClick={() => handleEdit(settlement.id)}
                            className="text-orange-600 hover:text-orange-800"
                            title="Editar"
                          >
                            <Edit className="w-5 h-5" />
                          </button>
                        )}
                        <button
                          onClick={() => handleExportIndividualReport(settlement.id)}
                          className="text-green-600 hover:text-green-800"
                          title="Exportar Excel"
                        >
                          <FileSpreadsheet className="w-5 h-5" />
                        </button>
                        {settlement.status !== 'paid' && (
                          <button
                            onClick={() => handleDelete(settlement.id)}
                            className="text-red-600 hover:text-red-800"
                            title="Eliminar"
                          >
                            <Trash2 className="w-5 h-5" />
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {filteredSettlements.length === 0 && (
            <div className="text-center py-12">
              <DollarSign className="w-16 h-16 mx-auto text-gray-300 mb-4" />
              <p className="text-gray-500">No se encontraron liquidaciones</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default SettlementsModuleEnhanced;
